spring.application.name=aurelia-jewelry-store
server.port=8081

# Configured for cloud instances (Use mem profiles or linked database paths when deploying live)
spring.datasource.url=jdbc:h2:mem:fancy-jewels;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true